### ISSUE TITLE
Plugins support

### ISSUE THREAD

**Issue by christianalfoni** [Yomguithereal/kotatsu#101]
It would be great to handle Babel plugins with `--plugins` the same way as `--presets`. Typically people use `babel-plugin-transform-decorators-legacy`.

I can make a pull if the idea is good :-)

**Comment by Yomguithereal** [comment]
Hello @christianalfoni. This would be nice indeed. My only concern is the ambiguity of the `plugins` here. You wouldn't know then a

**Comment by Yomguithereal** [comment]
Note that an alternative is also to have a babelrc file or a babel config in the package.json and use the `--babel` option.

**Comment by christianalfoni** [comment]
Ah, yeah, good point. It worked out completely fine using own config :) Really amazing to see how little configuration is needed!

Let me close this as plugins is easily solved

**Comment by Yomguithereal** [comment]
Happy to know it's useful to you :)
