### ISSUE TITLE
Copy headers

### ISSUE THREAD

**Issue by christianalfoni** [Yomguithereal/kotatsu#104]
When doing proxy the headers set by your express app are not copied over to the proxied response.

For example I had to add this on the http-proxy-middleware

```js
        onProxyRes: function (proxyRes, req, res) {
          res.append('set-cookie', proxyRes.headers['set-cookie']);
        }
```

Not sure what is the best approach here, if it should just copy everything. Just cookies, or it should be configured?

**Comment by christianalfoni** [comment]
The same applies for `onProxyReq`

**Comment by Yomguithereal** [comment]
Fist I need to update the `http-proxy-middleware` dependency. Doesn't it handle this kind of thing automatically?

**Comment by christianalfoni** [comment]
Sadly it does not :-/ Could not find any documentation on it.

**Comment by christianalfoni** [comment]
Would you mind me creating a pull which just copies the headers on the way in and on the way back? :-) Or you want to solve it differently?

**Comment by Yomguithereal** [comment]
I agree with the solution. The only complex thing here is that there may be some headers you might not want to overwrite. Cannot find a real use case right now. Just a hunch there. Anyway, I'll accept a PR for it if you do so.

**Comment by Yomguithereal** [comment]
Plus can you describe a use case where you want the headers to be copied please? Session cookies?

**Comment by christianalfoni** [comment]
Great :) Session cookies is the number one reason. Yeah, I can see your point, though you would not do this proxying in production. Which means you really do want your headers to be exactly the same between passing the proxy in this sort of environment? But yeah, hunches often become truths ;-) Though think it is better to default to copying all headers and move from there than not copying any of them. Forking and creating pull now :)

**Comment by christianalfoni** [comment]
https://github.com/Yomguithereal/kotatsu/pull/106
