### ISSUE TITLE
Sourcemaps on server errors

### ISSUE THREAD

**Issue by christianalfoni** [Yomguithereal/kotatsu#105]
Do not have my head completely around how the server runs, but it gives errors to the `bundle.js` file when server has errors. Would be good with some sourcemaps there somehow?

**Comment by Yomguithereal** [comment]
Just enable sourcemaps though the `-s` option and you shall have source maps on the server.

**Comment by christianalfoni** [comment]
Ah, sorry, maybe that should be default? Can not imagine you do not want source maps when developing? :)

**Comment by Yomguithereal** [comment]
Yes, this has to be discussed. The main drawback of source maps here is performance overhead. But I guess you are right. I will close this issue. Can you re-open another one stating that we should enable source-maps by default please?
