### ISSUE TITLE
Add sourcemaps by default on server

### ISSUE THREAD

**Issue by christianalfoni** [Yomguithereal/kotatsu#107]
Should have sourcemaps by default on server. Reference for different sourcemaps:

https://webpack.github.io/docs/configuration.html#devtool

**Comment by Yomguithereal** [comment]
If sourcemaps are default on the server, I guess they also should be default for the client. Else we'll introduce a weird bias.

**Comment by christianalfoni** [comment]
Good point, though a bit more difficult there. Because there are so many options and what library, your need to use breakpoints etc. affects that. Its kinda crazy :) On the server though there is really only one option I believe.

Hm hm, though could of course have a default on client too yes

**Comment by Yomguithereal** [comment]
Yup, but worry not, you still have the `--devtool` argument.

**Comment by Yomguithereal** [comment]
We can discuss the default devtool however. For the time being, it is `source-map` but should it be `#source-map` or else?

**Comment by christianalfoni** [comment]
It should be `cheap-eval-source-map`, superfast. Though not perfectly sure how it works on server bundle. But yeah, ideally that one. Or `cheap-module-eval-source-map` :)

**Comment by Yomguithereal** [comment]
This methods has real drawbacks however. It is fast to compute indeed but the `eval` running in the client can take up to ~10 sec to boot my apps sometimes.

**Comment by christianalfoni** [comment]
It can? Wow, have not thought of that at all really. Been only focused on rebundle speed. Thats a good point.

**Comment by Yomguithereal** [comment]
Will stick to `source-map` for the time being. Time will tell :)

**Comment by christianalfoni** [comment]
:+1:
