### ISSUE TITLE
Eating up promises?

### ISSUE THREAD

**Issue by christianalfoni** [Yomguithereal/kotatsu#108]
It seems that promises are not propagating with Kotatsu. Not sure why, might be Babel loading some crappy polyfill or something? Seen it happen in the browser. Not sure how to test, but rather painfull. Using a module that works fine separately in Node, but running with kotatsu the errors get swallowed somehow?

I can create an example as soon as I get some time :)

**Comment by Yomguithereal** [comment]
Well this is cumbersome indeed. Let me know when you find the use case so we can bust this bug.

**Comment by christianalfoni** [comment]
You are not adding the Babel polyfill somewhere? I know the Babel promise polyfill could override the native one in the browser which catches any errors not manually caught.

**Comment by Yomguithereal** [comment]
No. I don't add the Babel polyfill.

**Comment by Yomguithereal** [comment]
Or else the polyfill is sneaky and includes itself without my knowledge :).

**Comment by christianalfoni** [comment]
Not having a project to track progress here now, so will clean up issues list for you a bit :)
