### ISSUE TITLE
process.getuid is not a function

### ISSUE THREAD

**Issue by armandomendivil** [Yomguithereal/kotatsu#114]
I have a problem when i run kotatsu command

return process.getuid is not a function

i'm using windows ;/ with node v4.3.1

**Comment by Yomguithereal** [comment]
Hello @armandomendivil. It's because `process.getuid` doesn't exist on windows :). Let me fix this for you.

**Comment by Yomguithereal** [comment]
@armandomendivil I published `0.12.1` on npm with a fix. Can you tell me whether this fixes your issue please? I have currently no way of testing on windows to assert the fix worked.

**Comment by armandomendivil** [comment]
@Yomguithereal  Thank you so much! but when i try to run kotatsu command return error:

[kotatsu] (v0.12.1)
[kotatsu] Compiling...
[kotatsu] Done!
[kotatsu] Starting your script...
module.js:327
    throw err;
    ^

Error: Cannot find module 'C:UsersarmandoAppDataRoaming
pm
ode_moduleskotatsu
ode_modulessource-map-supportsource-map-support.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\dev\webpack\kotatsu\.kotatsu\bundle.js:1:63)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
 [kotatsu] The script crashed. Waiting for changes to reload...

I have tried many solutions I've looked on internet, but none has helped me :(

**Comment by Yomguithereal** [comment]
@armandomendivil I know where the problem comes from. It's also a windows specific quirk. Until I fix this, you can just disable source maps through `--no-source-maps` and it should work.

**Comment by armandomendivil** [comment]
Thanks a lot! it works now! one thing, in your express example you need to add `module.exports = app;` =) Thanks again! this is very helpful!

**Comment by Yomguithereal** [comment]
I opened #123 to tackle the other bug you are having relating to source maps.

**Comment by Yomguithereal** [comment]
Hello @armandomendivil. Just releases `0.12.2`. This should let you use source maps on windows normally.
