### ISSUE TITLE
Should "kotatsu build client" output index.html too?

### ISSUE THREAD

**Issue by bebraw** [Yomguithereal/kotatsu#117]
Currently `kotatsu build client` outputs just a bundle and a sourcemap related to it. This is likely just fine if you serve the bundle yourself.

In my case I'm generating a whole app (index.html, app.js, vendor.js) to push into GitHub Pages. Previously I've used [html-webpack-plugin](https://www.npmjs.org/package/html-webpack-plugin) to generate the **index.html** and references to my scripts.

Do you think kotatsu should have this sort of functionality integrated to it or should I handle it on my side?

**Comment by Yomguithereal** [comment]
That's a good question indeed. I'd say that you should handle it on your side because any "production" app is unlikely not to need a custom html file anyway. But let's take some time to think about it.

**Comment by bebraw** [comment]
Yeah, I can handle it. As mentioned in another issue, this is likely something I should deal with it through **webpack-presets** so I get something nice to maintain.
