### ISSUE TITLE
How to deal with output file name hashing?

### ISSUE THREAD

**Issue by bebraw** [Yomguithereal/kotatsu#118]
To get better cache behavior, it can be handy to attach a hash to your output filename. One common way to achieve this in webpack is to use `chunkhash`. There are some gotchas, but it's fairly cool.

I tried the approach with kotatsu like this:

**webpack.config.js**

```javascript
output: {
  path: PATHS.build,
  filename: '[name].[chunkhash].js',
  chunkFilename: '[chunkhash].js'
},
```

**package.json**

```json
    "build": "kotatsu build client --babel --minify --config ./webpack.config.js",
```

This yielded

```bash
kotatsu-demo [master] $ ls -la build/
total 12560
drwxr-xr-x   6 juhovepsalainen  staff      204 Mar  2 15:10 .
drwxr-xr-x  10 juhovepsalainen  staff      340 Mar  2 15:00 ..
-rw-r--r--   1 juhovepsalainen  staff   322102 Mar  2 15:07 bundle.js
-rw-r--r--   1 juhovepsalainen  staff  2890000 Mar  2 15:07 bundle.js.map
-rw-r--r--   1 juhovepsalainen  staff   322121 Mar  2 15:10 main.efe845d2445926cd9b08.js
-rw-r--r--   1 juhovepsalainen  staff  2890057 Mar  2 15:10 main.efe845d2445926cd9b08.js.map
```

So I'm guessing there's some `concat` magic going on that gives that `bundle` part. `main` seems to come based on my configuration.

How would you deal with this?

Btw, you can find the full code at my [demo repo](https://github.com/survivejs/kotatsu-demo). I'm trying to make it as neat as possible (as much kotatsu as possible).

**Comment by Yomguithereal** [comment]
I guess I just merged the output a bit fast and forgot about those. Let me check that.

**Comment by Yomguithereal** [comment]
Just checked this and webpack tells me you should use `hash` rather than `chunkhash`.

**Comment by Yomguithereal** [comment]
Upon doing so, my build folder receive only two files and no `bundle.js.*` files.

**Comment by bebraw** [comment]
`chunkhash` is handy when you set up bundle splitting (unique hash per chunk literally). That's what I would like to achieve ideally. Here's [the complete setup](https://github.com/survivejs/react-component-boilerplate). You can probably grasp the approach better by checking out [my chapter](http://survivejs.com/webpack_react/building_kanban/) about the techniques.

I guess the question is how much kotatsu itself should do. I could use both kotatsu and [webpack-presets](https://github.com/survivejs/webpack-presets) to achieve tasks I need while keeping it relatively light still. It's especially valuable that kotatsu deals with hot loading and such. There are still bigger questions like how to handle custom testing setups in a sane way.

**Comment by Yomguithereal** [comment]
So here, you are suggesting I use chunkhashes by default to speed some operations? Is that it?

**Comment by bebraw** [comment]
@Yomguithereal I'm not sure if it has any speed effect. You are going to need `chunkhash` with bundle splitting. I don't think you are going to need it by default, though.

If you want speed, perhaps researching [DllPlugin](https://github.com/webpack/webpack/tree/master/examples/dll) would be worthwhile.

**Comment by Yomguithereal** [comment]
So is there still something to do about this issue or should I close it?

**Comment by bebraw** [comment]
@Yomguithereal If you override `output` configuration, perhaps it shouldn't generate `bundle.js` then?

**Comment by Yomguithereal** [comment]
It doesn't generate `bundle.js` on my end.

**Comment by bebraw** [comment]
Yeah, let's close this.

I see now it doesn't clean the build output between the builds so you can end up with old build artifacts as hashes change etc. I can solve this on my side, though.
