### ISSUE TITLE
Kotatsu should return a non 0 exit status when the build fails

### ISSUE THREAD

**Issue by SeeThruHead** [Yomguithereal/kotatsu#120]
I've come across an interesting dilemma. Kotatsu isn't failing when it doesn't find a module.
Example:
```
 ~/C/i/thinky-fe   master ±  npm run build; echo $status

> thinky-frontend@0.0.1-rc1 build /Users/dev/Code/infl/thinky-fe
> rm -rf build && NODE_ENV=production kotatsu -c webpack.config.js -s false --babel build client

[kotatsu] (v0.12.1)
[kotatsu] Compiling...
[kotatsu] ./src/card-list/components/card-list.js
Module not found: Error: Cannot resolve module 'thinky-card' in /Users/dev/Code/infl/thinky-fe/src/card-list/components
...
 @ ./src/card-list/components/card-list.js 11:18-40
0 <--- huh?
 ~/C/i/thinky-fe   master ±  la build
total 408
drwxr-xr-x   5 dev  staff   170B 11 Mar 15:46 .
drwxr-xr-x  21 dev  staff   714B 11 Mar 15:46 ..
-rw-r--r--   1 dev  staff    84K 11 Mar 15:46 main.3c003bd50448683099d2.js
-rw-r--r--   1 dev  staff    96B 11 Mar 15:46 manifest.json
-rw-r--r--   1 dev  staff   112K 11 Mar 15:46 vendor.a23e6144a5995509ddac.js
```

It even builds some of the files

is this intended?

**Comment by Yomguithereal** [comment]
No it's not normal. But I wonder whether webpack works like this also or not. Anyway, I should probably detect this case and exit on a 1.

**Comment by SeeThruHead** [comment]
Weback returns exit status 1 if it doesn’t find a module.

-- 
Shane Keulen
Sent with Airmail

On March 11, 2016 at 4:55:44 PM, Guillaume Plique (notifications@github.com) wrote:

No it's not normal. But I wonder whether webpack works like this also or not. Anyway, I should probably detect this case and exit on a 1.
