### ISSUE TITLE
HMR Does Not Perform Swap

### ISSUE THREAD

**Issue by iantanwx** [Yomguithereal/kotatsu#128]
Hello Guillaume, and great work! Loving Kotatsu and I hope you maintain it for a long time to come.

I'm having an issue using Kotatsu with HMR -- `kotatsu start --es2015 index.js` prints:

```
[kotatsu] (v0.13.0)
[kotatsu] Compiling...
[kotatsu] Done!
[kotatsu] Starting your script...
[kotatsu] HMR connected.
```

`index.js` is as follows:

```
import app from './config/express';
import http from 'http';

const server = http.createServer(app);
const debug = require('debug')('ms-boilerplate:index');

server.listen(8888);

// listen on port config.port
if (module.hot) {
    module.hot.accept('./config/express.js', () => {
        server.removeListener('request', app);
        let express = require('./config/express.js');
        server.on('request', express);
        debug('Server reloaded.');
    });
}

export default app;
```

express.js contains the standard express configuration, where the usual middleware etc. gets set up. When I edit and save express.js however, HMR doesn't seem to rebuild the bundle. It's worth mentioning that nodemon also appears to fail; it doesn't trigger the tasks (in gulp) that it should trigger. I thought this might have been an issue with OS X, so I spun up a fresh VM and tried again -- but the same issue results with both kotatsu and nodemon.

All routes work when I test them with swagger-ui; but HMR (or the file watcher) seems to refuse to rebuild on any changes. 

Any help would be greatly appreciated. Cheers!

**Comment by Yomguithereal** [comment]
Hello @iantanwx. This is quite strange indeed. Can you try to change this line:

```js
let express = require('./config/express.js');
``` 

into this:

```js
let express = require('./config/express.js').default;
```

and tell me whether this does the trick?

**Comment by iantanwx** [comment]
@Yomguithereal Unfortunately that doesn't solve the problem. It might be a problem with OS X...

**Comment by Yomguithereal** [comment]
Can you send me a whole use case so I can test this on my end and find the issue?

**Comment by iantanwx** [comment]
@Yomguithereal Most certainly sir, let me clone my info, remove my tokens, and I'll put you on it.

**Comment by iantanwx** [comment]
Ok, I added you to the repo @Yomguithereal

**Comment by Yomguithereal** [comment]
Ok, so I tried the repo, installed the deps, started the server and, after I changed this line:

```js
let express = require('./config/express.js').default;
```

the HMR does work (else it will fire an error because without the default you are trying to attach an undefined handler and the event emitter does not like that).

**Comment by iantanwx** [comment]
@Yomguithereal I think it's an issue with OS X on this particular machine. I ran the same repo on my MBP and everything worked out fine. It seems it's just this machine, sorry for the hassle.
