### ISSUE TITLE
Universal javascript example?

### ISSUE THREAD

**Issue by cloud-walker** [Yomguithereal/kotatsu#132]
I've tried kotatsu on a dummy project, it work pretty well, but i'm trying to accomplish a universal application, and I'm stuck on combine node example with react example...

**Comment by Yomguithereal** [comment]
Hello @cloud-walker. What is specifically holding you back with kotatsu there? I am trying to understand whether there is an issue with the tool or if you fail to boot an app that is universal using the tool.

**Comment by cloud-walker** [comment]
I've crafted a demo for the occasion.

It seems to work but I dont get how to connect the client-side bundling to the rest of the process, for now i'm using kotetsu build, but it bundle only without watch, maybe I'm missing something, this new hot reloading thing is a bit hard to grasp T_T

https://github.com/cloud-walker/kotatsu-demo

**Comment by ndelangen** [comment]
I'm interested in an example of universal JavaScript using this library from the author as well. Preferably with react.
