### ISSUE TITLE
Build command?

### ISSUE THREAD

**Issue by Yomguithereal** [Yomguithereal/kotatsu#46]

**Comment by glenjamin** [comment]
I'd like `build` so that I can verify the bundle would build - just as a smoke test to run on CI.

**Comment by Yomguithereal** [comment]
Will probably do that this sunday. Do you think the command should build for production by default (-p webpack with uglify). Or only on demand?

**Comment by glenjamin** [comment]
Only on demand I'd say - my particular use-case is I want to have CI check that `kotatsu serve` would work when someone checks out the repo.

Is using `kotatsu` for production builds a goal?

**Comment by Yomguithereal** [comment]
I guess not but it would be strange to make people download and use the full stack tools they want to avoid when using this tool to build a minified version. Anyway, I guess not minifying etc. by default will be the way to go.

**Comment by glenjamin** [comment]
I guess it depends on your goals, here's 3 distinct scenarios that might lead someone to use kotatsu

1. Example / Demo projects which never need a truly production build
2. Newcomers who want to dive into building, and worry about production builds later
3. Experienced people who can't be bothered to do their setup themselves

Afaik your original aim for for camp 2. I'm currently in camp 1, but on other projects I'm often in camp 3.

The requirements for 1 and 2 are similar, but 3 would potentially need a lot of flexibility.

It might be best to focus on 1 and 2, and provide a guide to migrate away for when people need to transition into production and take full control of the setup?
