### ISSUE TITLE
Add support to pass arguments to the script on start command

### ISSUE THREAD

**Issue by esnunes** [Yomguithereal/kotatsu#50]
In order to support `process.argv` kotatsu must forward arguments to the script during start command. I would like to run:
```bash
kotatsu start --output ./dist src/index.js my-arg-1
```
and be able to read `my-arg-1` using:
```js
process.argv[2]
```

**Comment by Yomguithereal** [comment]
Hello @esnunes. I would use the standard technique of the `--` at the end of the command to pass arguments. This is how a lot of unix tools (notably npm also) solve this issue:

```js
kotatsu start --output ./dist src/index.js -- --my-arg1
```

**Comment by esnunes** [comment]
Hi @Yomguithereal, that would be perfect.

**Comment by Yomguithereal** [comment]
This should be easy to add since I use `yargs`. Will do this tomorrow.

**Comment by Yomguithereal** [comment]
Done! By the way, would you know a easy way to unit test the library?

**Comment by esnunes** [comment]
In case you are directly using yargs library I believe you don't have to test it. If you want to ensure the argument options are ok and yargs is not guessing it wrong I would suggest not to use yargs and use commander arguments.

**Comment by Yomguithereal** [comment]
No problems with yargs so far. I did not mean how to unit test the CLI argument but the whole tool.

**Comment by esnunes** [comment]
Sorry, I got it wrong. I might not be the right person to support you on testing, although I do it sometimes, I'm not expert on it :(.
