### ISSUE TITLE
Add support to babel-polyfill

### ISSUE THREAD

**Issue by esnunes** [Yomguithereal/kotatsu#51]
I tried to use babel with preset `stage-0` and I got the following error message:
```
webpack regeneratorRuntime is not defined
```
Babel requires that I add `babel-polyfill` to fix this issue. As kotatsu is using webpack to compile it would be nice to add `babel-polyfill` as the first entry. I tried to use a custom webpack.config file but the entry config option is not merged (it may be hard to decide how to merge it, you might want to add your entries after or before the default ones).

To be able to modify `entry` as any other array inside webpack config you need to pass an additional argument to lodash `merge` as following:
```js
_.merge(object, other, function(a, b) {
  if (_.isArray(a)) {
    return a.concat(b);
  }
});
```

My *workaround* at the moment is adding `import 'babel-polyfill'` in the first line of by start script.

**Comment by Yomguithereal** [comment]
This is indeed a sensible issue @esnunes. I need to think about merging a bit more. For the time being, one cannot fail to provide an entry but I guess it would be viable if the entry is already in the webpack config.
