### ISSUE TITLE
--devtool has no effect without --source-maps

### ISSUE THREAD

**Issue by glenjamin** [Yomguithereal/kotatsu#66]
Not sure if this is intended or not, it caught me out when I tried to replace `--source-maps` with `--devtool eval-source-map`

**Comment by Yomguithereal** [comment]
Problem on my side. `--devtool` doesn't enable `--source-maps` if the latter is not given. Let me fix this.

**Comment by Yomguithereal** [comment]
Thanks for the bug-busting :).

**Comment by Yomguithereal** [comment]
Published `0.4.2`.
