### ISSUE TITLE
Use same major lodash version as babel

### ISSUE THREAD

**Issue by glenjamin** [Yomguithereal/kotatsu#67]
This will speed up installs, avoiding the following scenario:

<img width="535" alt="screen shot 2016-01-15 at 21 50 34" src="https://cloud.githubusercontent.com/assets/151272/12366280/0b609fac-bbd2-11e5-86a9-f9947a00dd73.png">

**Comment by Yomguithereal** [comment]
This seems sensible indeed. Will need to change back to v4 when Babel updates itself.
