### ISSUE TITLE
Print kotatsu log into stderr

### ISSUE THREAD

**Issue by Yomguithereal** [Yomguithereal/kotatsu#73]
@boogheta should I write kotatsu's log into stderr so that the spawned script's log might be piped into something else?

**Comment by boogheta** [comment]
As we discussed, I feel like it would be a bit extreme and unexpected, I would allow it though, but as a keyword argument such as --stderr so that one can indeed use it if he likes, but the regular use doesn't generate unexpected output.

**Comment by Yomguithereal** [comment]
Fair enough. I will resume the development of such an option when backed by a real use case then.
