### ISSUE TITLE
Why "The following modules couldn't be hot updated" ?

### ISSUE THREAD

**Issue by cr0cK** [Yomguithereal/kotatsu#75]
Hi,

I'm trying to use kotatsu on a simple Express project, just to see how it works before using it on a larger project.

I just setup a project, edit a file and got this warning.

I looked at the source but can't figure out exactly why my module can't be hotreloaded and because kotatsu doesn't restart the server (yet?) itself, I have to stop and restart the server manually.

Have I miss something?

Thanks.

**Comment by Yomguithereal** [comment]
Hello @cr0cK. HMR is opt-in so did you correctly setup the express app start using the `module.hot.accept` API? Like shown [here](https://github.com/Yomguithereal/kotatsu#express).

Also, if you can show me your code, I should be able to help you better.

**Comment by cr0cK** [comment]
Finally, it's ok. I was trying to reload the main script... Sorry.

**Comment by Yomguithereal** [comment]
Good to know it's fixed :smile:.
