### ISSUE TITLE
Which configuration file are need

### ISSUE THREAD

**Issue by lionelB** [Yomguithereal/kotatsu#96]
Hello,
Silly question incoming :D 
Coming from webpack-dev-server, some config files seems not needed anymore.
Should I need to provide a `.babelrc` or `babel-loader` inside my custom webpack.config file ?

**Comment by lionelB** [comment]
also since kotatsu take care of devtools, what happen if I also add a `devtools: source-map`in my webpack config file
same for entry, output.

**Comment by Yomguithereal** [comment]
> also since kotatsu take care of devtools, what happen if I also add a devtools: source-mapin my webpack config file

The CLI options will take precedence over the webpack config. However, if you do not specify CLI options, then your webpack config will be taken as reference.

**Comment by Yomguithereal** [comment]
> Should I need to provide a .babelrc or babel-loader inside my custom webpack.config file ?

Whatever you prefer. If you just use babel 6 presets, you can also use the `--presets` option of the CLI tool if you need.

**Comment by lionelB** [comment]
so if I don't use --presets, .babelrc will be use ? Am I right ?

**Comment by Yomguithereal** [comment]
Yup.

**Comment by Yomguithereal** [comment]
Just be sure to enable babel through `--babel` at least.

**Comment by Yomguithereal** [comment]
@lionelB just released `0.10.0`. It should fix all the bugs you are having. Can you tell me if it's really the case so I can assess what remains to be fixed?
