### ISSUE TITLE
Postcss loader seems not working

### ISSUE THREAD

**Issue by lionelB** [Yomguithereal/kotatsu#97]
Hello
I have trouble with postcss-loader.
from my webpack.config.babel.js
```js
{
module: {
  loaders: [{
      test: /\.css$/,
      loader: ExtractTextPlugin.extract("style-loader", "css-loader!postcss-loader")
    }]
  },
  postcss: () => [
    require("postcss-import")({
      addDependencyTo: webpack,
      path: [
        path.join(__dirname, 'node_modules'),
        path.join(__dirname, 'src')
      ]
    }),
    require("postcss-url"),
    require("postcss-cssnext")
  ]
```

postcss use a special key from the webpack config to work.

**Comment by Yomguithereal** [comment]
@lionelB, that is weird. Let me check if the config is merge correctly by kotatsu.

**Comment by Yomguithereal** [comment]
Is your project available somewhere so I can help you better?

**Comment by lionelB** [comment]
not yet but I can push it :)

**Comment by Yomguithereal** [comment]
As you wish :).

**Comment by lionelB** [comment]
take a look here https://github.com/lionelB/lumographe.fr/tree/reboot

**Comment by lionelB** [comment]
note this is a big Work In Progress

**Comment by Yomguithereal** [comment]
I promise I won't judge.

**Comment by Yomguithereal** [comment]
I notice that I should probably finish up plugins' merging.

**Comment by Yomguithereal** [comment]
Ok, I see where this went wrong. Damn Babel `.default` thingy...

**Comment by Yomguithereal** [comment]
Let me fix all that in the afternoon/evening.

**Comment by lionelB** [comment]
thanks a looooot

**Comment by lionelB** [comment]
Hi,
I've open a bunch of issue but I didn't manage to make kotatsu working using my current webpack.config file having weird eslint issues (like it tries to lint the transpiled file :/ )  
I need to craft a smaller webconfig file (entry and specific loaders for file / css) and made a fresh test.

 I confess I switch to webpack-dev-server but I definitly looking for a simpler solution to start with new project
